version: '3.7'

services:
  nginx-grpc:
    environment:
      TZ: GMT-3
      NGINX_SERVER_NAME: nginx-grpc.localhost
      GRPC_SERVER_1: grpc-customers1:40051
      GRPC_SERVER_2: grpc-customers2:50051
      API_KEY: your key amplify nginx

  api-gateway-grcp:
    environment:
      DEBUG: 0
      TZ: "America/Fortaleza"
      MAX_MEMORY_RESTART: 384M
      URL_CUSTOMERS: your ip host:8085
      URL_USERS: grpc-users:50052
      URL_PRODUCTS: grpc-products:50053
      URL_ORDERS: grpc-orders:50054