version: '3.7'

services:
  nginx-grpc:
    environment:
      TZ: GMT-3
      NGINX_SERVER_NAME: nginx-grpc.localhost
      GRPC_SERVER_1: grpc-customers1:40051
      GRPC_SERVER_2: grpc-customers2:50051
      API_KEY: your key amplify nginx

  api-gateway-grcp:
    links:
      - mysql-api-gateway-grcp
      - nginx-grpc
      - grpc-users
      - grpc-products
      - grpc-orders
    depends_on:
      - mysql-api-gateway-grcp
      - nginx-grpc
      - grpc-users
      - grpc-products
      - grpc-orders
    volumes:
      - ./app-gateway:/application:cached
      - yarn-cache:/root/.cache/yarn/v1:cached
    entrypoint: ["entrypoint-server.sh"]


  mysql-api-gateway-grcp:
    container_name: mysql-api-gateway-grcp
    image: mysql:5.7
    ports:
      - 33009:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: api-gateway-grcp
      MYSQL_USER: root
      MYSQL_PASSWORD: root@2020
      MYSQL_ROOT_PASSWORD: root@2020

volumes:
  dbdata: ~
  yarn-cache:
    name: yarn-cache