version: '3.7'

services:
  grpc-customers1:
    container_name: grpc-customers1
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    environment:
      PORT: 40051
    ports:
      - 40051:40051
    volumes:
      - ./app-customers:/opt/app
    entrypoint: ["entrypoint-microservices.sh"]

  grpc-customers2:
    container_name: grpc-customers2
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    environment:
      PORT: 50051
    ports:
      - 50051:50051
    volumes:
      - ./app-customers:/opt/app
    entrypoint: ["entrypoint-microservices.sh"]

  grpc-users:
    container_name: grpc-users
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    ports:
      - 50052:50052
    volumes:
      - ./app-users:/opt/app
    entrypoint: ["entrypoint-microservices.sh"]

  grpc-products:
    container_name: grpc-products
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - 50053:50053
    volumes:
      - ./app-products:/opt/app
    entrypoint: ["entrypoint-server.sh"]

  grpc-orders:
    container_name: grpc-orders
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - 50054:50054
    volumes:
      - ./app-orders:/opt/app
    entrypoint: ["entrypoint-server.sh"]

  nginx-grpc:
    container_name: nginx-grpc
    hostname: "${HOST_NAME}"
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8085:80
    links:
      - grpc-customers1
      - grpc-customers2
    depends_on:
      - grpc-customers1
      - grpc-customers2
    volumes:
      - ./docker/nginx/logs/nginx:/var/log/nginx

  api-gateway-grcp:
    container_name: api-gateway-grcp
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    ports:
      - 3005:3005
    links:
      - nginx-grpc
      - grpc-users
      - grpc-products
      - grpc-orders
    depends_on:
      - nginx-grpc
      - grpc-users
      - grpc-products
      - grpc-orders
    volumes:
      - ./app-gateway:/opt/app
    entrypoint: ["entrypoint-server.sh"]