version: '3.7'

x-logging:
  &default-logging
  options:
    max-file: "5"
    max-size: "10m"
  driver: "json-file"

x-sysctls:
  &default-sysctls
  net.core.somaxconn: 250000
  net.ipv4.tcp_keepalive_time: 300
  net.ipv4.tcp_max_syn_backlog: 2500
  net.ipv4.tcp_syncookies: 0
  net.ipv4.ip_forward: 1
  net.ipv4.tcp_tw_reuse: 1
  net.ipv4.tcp_fin_timeout: 15

x-ulimits:
  &default-ulimits
  nproc: 65535
  nofile:
    soft: 20000
    hard: 40000

services:
  api-grpc-server:
    container_name: api-grpc-server
    image: docker/api-grpc-server
    logging: *default-logging
    sysctls: *default-sysctls
    ulimits: *default-ulimits
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    environment:
      TZ: "America/Fortaleza"
    ports:
      - 50051:50051
    volumes:
      - ./app:/opt/app
    entrypoint: ["entrypoint-server.sh"]
