version: '3.7'

services:
  api-grpc-server:
    container_name: api-grpc-server
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    ports:
      - 50051:50051
    volumes:
      - ./app:/opt/app
    entrypoint: ["entrypoint-server.sh"]
