version: '3.7'

services:
  grpc-customers:
    container_name: grpc-customers
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    ports:
      - 50051:50051
    volumes:
      - ./app-customers:/opt/app
    entrypoint: ["entrypoint-server.sh"]

  grpc-users:
    container_name: grpc-users
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    ports:
      - 50052:50052
    volumes:
      - ./app-users:/opt/app
    entrypoint: ["entrypoint-server.sh"]

  grpc-products:
    container_name: grpc-products
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - 50053:50053
    volumes:
      - ./app-products:/opt/app
    entrypoint: ["entrypoint-server.sh"]



  api-gateway-grcp:
    container_name: api-gateway-grcp
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    ports:
      - 3005:3005
    links:
      - grpc-customers
      - grpc-users
      - grpc-products
    depends_on:
      - grpc-customers
      - grpc-users
      - grpc-products
    volumes:
      - ./app-gateway:/opt/app
    entrypoint: ["entrypoint-server.sh"]