# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import products_pb2 as products_dot_products__pb2


class ProductsStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAll = channel.unary_unary(
                '/Products/GetAll',
                request_serializer=products_dot_products__pb2.Empty.SerializeToString,
                response_deserializer=products_dot_products__pb2.ProductsResponseList.FromString,
                )
        self.Get = channel.unary_unary(
                '/Products/Get',
                request_serializer=products_dot_products__pb2.ProductsRequestId.SerializeToString,
                response_deserializer=products_dot_products__pb2.ProductsResponse.FromString,
                )
        self.Insert = channel.unary_unary(
                '/Products/Insert',
                request_serializer=products_dot_products__pb2.ProductsInsertRequest.SerializeToString,
                response_deserializer=products_dot_products__pb2.ProductsResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/Products/Update',
                request_serializer=products_dot_products__pb2.ProductsUpdateRequest.SerializeToString,
                response_deserializer=products_dot_products__pb2.ProductsResponse.FromString,
                )
        self.Remove = channel.unary_unary(
                '/Products/Remove',
                request_serializer=products_dot_products__pb2.ProductsRequestId.SerializeToString,
                response_deserializer=products_dot_products__pb2.Empty.FromString,
                )


class ProductsServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAll': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=products_dot_products__pb2.Empty.FromString,
                    response_serializer=products_dot_products__pb2.ProductsResponseList.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=products_dot_products__pb2.ProductsRequestId.FromString,
                    response_serializer=products_dot_products__pb2.ProductsResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=products_dot_products__pb2.ProductsInsertRequest.FromString,
                    response_serializer=products_dot_products__pb2.ProductsResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=products_dot_products__pb2.ProductsUpdateRequest.FromString,
                    response_serializer=products_dot_products__pb2.ProductsResponse.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=products_dot_products__pb2.ProductsRequestId.FromString,
                    response_serializer=products_dot_products__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Products', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Products(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Products/GetAll',
            products_dot_products__pb2.Empty.SerializeToString,
            products_dot_products__pb2.ProductsResponseList.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Products/Get',
            products_dot_products__pb2.ProductsRequestId.SerializeToString,
            products_dot_products__pb2.ProductsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Products/Insert',
            products_dot_products__pb2.ProductsInsertRequest.SerializeToString,
            products_dot_products__pb2.ProductsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Products/Update',
            products_dot_products__pb2.ProductsUpdateRequest.SerializeToString,
            products_dot_products__pb2.ProductsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Products/Remove',
            products_dot_products__pb2.ProductsRequestId.SerializeToString,
            products_dot_products__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
