# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products/products.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='products/products.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x17products/products.proto\"\x07\n\x05\x45mpty\"4\n\x15ProductsInsertRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\"@\n\x15ProductsUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\"\x1f\n\x11ProductsRequestId\x12\n\n\x02id\x18\x01 \x01(\t\";\n\x10ProductsResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\"G\n\x14ProductsResponseList\x12/\n\x14productsResponseList\x18\x01 \x03(\x0b\x32\x11.ProductsResponse2\xfb\x01\n\x08Products\x12)\n\x06GetAll\x12\x06.Empty\x1a\x15.ProductsResponseList\"\x00\x12.\n\x03Get\x12\x12.ProductsRequestId\x1a\x11.ProductsResponse\"\x00\x12\x35\n\x06Insert\x12\x16.ProductsInsertRequest\x1a\x11.ProductsResponse\"\x00\x12\x35\n\x06Update\x12\x16.ProductsUpdateRequest\x1a\x11.ProductsResponse\"\x00\x12&\n\x06Remove\x12\x12.ProductsRequestId\x1a\x06.Empty\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=34,
)


_PRODUCTSINSERTREQUEST = _descriptor.Descriptor(
  name='ProductsInsertRequest',
  full_name='ProductsInsertRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ProductsInsertRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='ProductsInsertRequest.price', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=88,
)


_PRODUCTSUPDATEREQUEST = _descriptor.Descriptor(
  name='ProductsUpdateRequest',
  full_name='ProductsUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ProductsUpdateRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ProductsUpdateRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='ProductsUpdateRequest.price', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=154,
)


_PRODUCTSREQUESTID = _descriptor.Descriptor(
  name='ProductsRequestId',
  full_name='ProductsRequestId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ProductsRequestId.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=187,
)


_PRODUCTSRESPONSE = _descriptor.Descriptor(
  name='ProductsResponse',
  full_name='ProductsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ProductsResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ProductsResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='ProductsResponse.price', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=248,
)


_PRODUCTSRESPONSELIST = _descriptor.Descriptor(
  name='ProductsResponseList',
  full_name='ProductsResponseList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='productsResponseList', full_name='ProductsResponseList.productsResponseList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=321,
)

_PRODUCTSRESPONSELIST.fields_by_name['productsResponseList'].message_type = _PRODUCTSRESPONSE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ProductsInsertRequest'] = _PRODUCTSINSERTREQUEST
DESCRIPTOR.message_types_by_name['ProductsUpdateRequest'] = _PRODUCTSUPDATEREQUEST
DESCRIPTOR.message_types_by_name['ProductsRequestId'] = _PRODUCTSREQUESTID
DESCRIPTOR.message_types_by_name['ProductsResponse'] = _PRODUCTSRESPONSE
DESCRIPTOR.message_types_by_name['ProductsResponseList'] = _PRODUCTSRESPONSELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'products.products_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

ProductsInsertRequest = _reflection.GeneratedProtocolMessageType('ProductsInsertRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTSINSERTREQUEST,
  '__module__' : 'products.products_pb2'
  # @@protoc_insertion_point(class_scope:ProductsInsertRequest)
  })
_sym_db.RegisterMessage(ProductsInsertRequest)

ProductsUpdateRequest = _reflection.GeneratedProtocolMessageType('ProductsUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTSUPDATEREQUEST,
  '__module__' : 'products.products_pb2'
  # @@protoc_insertion_point(class_scope:ProductsUpdateRequest)
  })
_sym_db.RegisterMessage(ProductsUpdateRequest)

ProductsRequestId = _reflection.GeneratedProtocolMessageType('ProductsRequestId', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTSREQUESTID,
  '__module__' : 'products.products_pb2'
  # @@protoc_insertion_point(class_scope:ProductsRequestId)
  })
_sym_db.RegisterMessage(ProductsRequestId)

ProductsResponse = _reflection.GeneratedProtocolMessageType('ProductsResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTSRESPONSE,
  '__module__' : 'products.products_pb2'
  # @@protoc_insertion_point(class_scope:ProductsResponse)
  })
_sym_db.RegisterMessage(ProductsResponse)

ProductsResponseList = _reflection.GeneratedProtocolMessageType('ProductsResponseList', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTSRESPONSELIST,
  '__module__' : 'products.products_pb2'
  # @@protoc_insertion_point(class_scope:ProductsResponseList)
  })
_sym_db.RegisterMessage(ProductsResponseList)



_PRODUCTS = _descriptor.ServiceDescriptor(
  name='Products',
  full_name='Products',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=324,
  serialized_end=575,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='Products.GetAll',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_PRODUCTSRESPONSELIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='Products.Get',
    index=1,
    containing_service=None,
    input_type=_PRODUCTSREQUESTID,
    output_type=_PRODUCTSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Insert',
    full_name='Products.Insert',
    index=2,
    containing_service=None,
    input_type=_PRODUCTSINSERTREQUEST,
    output_type=_PRODUCTSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='Products.Update',
    index=3,
    containing_service=None,
    input_type=_PRODUCTSUPDATEREQUEST,
    output_type=_PRODUCTSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Remove',
    full_name='Products.Remove',
    index=4,
    containing_service=None,
    input_type=_PRODUCTSREQUESTID,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTS)

DESCRIPTOR.services_by_name['Products'] = _PRODUCTS

# @@protoc_insertion_point(module_scope)
